
- name: Deploy application to the web server
  hosts: webserver
  become: yes  # Use sudo to execute tasks
  tasks:
    - name: Copy index.html to the web server
      copy:
        src: /home/ansible/index.html  # Source file on the Ansible server
        dest: /var/www/html/index.html  # Destination on the web server
        mode: '0644'

    - name: Ensure the web server is running
      service:
        name: apache2
        state: started
        enabled: yes
